services:
  database:
    container_name: database
    image: model_production:postgres
    restart: always
    volumes:
      - ./postgres_dump:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      #- POSTGRES_DB=${POSTGRES_DB} 
      - POSTGRES_DB=fraud_transactions 
      #- POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
      - POSTGRES_PASSWORD=password1
    ports:
      - 5432:5432
  
  app:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: app_container
    depends_on:
      - database
    ports: 
      - '8080:8080'
      - '5001:5001'
    environment:
      # DATABASE: postgresql://postgres:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      DATABASE: postgresql://postgres:password1@database:5432/fraud_transactions
     
volumes:
  postgres_data:


