FROM python:3.9-slim-bullseye

COPY requirements_mlflow.txt /mlflow/
RUN pip install -r mlflow/requirements_mlflow.txt

COPY  ./mlruns /mlflow/mlruns
COPY  ./mlartifacts /mlflow/mlartifacts
COPY  ./utils /mlflow/utils
COPY  ./retrain_model.py /mlflow/

WORKDIR /mlflow

CMD ["python", "retrain_model.py"]
