services:
  app:
    entrypoint: ["/bin/bash"]
    #, "run_stop_server.sh"]
    command: ["-c", "mlflow server --host 0.0.0.0 --port 5001 & MLFLOW_PID=$! && sleep 60 && python retrain_model.py && kill -9 $MLFLOW_PID && docker stop app container && docker compose down"]
    # command: ["-c", "python hello.py"]
    
    
