FROM python:3.9-slim-bullseye

COPY requirements_mlflow.txt /src/
RUN pip install --upgrade pip
RUN pip install -r src/requirements_mlflow.txt

COPY  ./mlruns /src/mlruns
COPY  ./mlartifacts /src/mlartifacts
COPY  ./utils /src/utils
COPY  ./retrain_model.py /src/
COPY ./templates /src/templates/
COPY app.py /src/

WORKDIR /src
RUN echo 'Opening predictions app'
ENTRYPOINT [ "python" ] 
CMD ["app.py"]
