services:
  database:
    container_name: database
    image: postgres:latest
    restart: always
    volumes:
      - ./postgres_dump:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB} 
      - POSTGRES_PASSWORD=password1
    ports:
      - 5432:5432
  
  app:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    depends_on:
      - database
    ports: 
      - '8080:8080'
      - '5001:5001'
    environment:
      DATABASE: postgresql://postgres:password1@database:5432/fraud_transactions
     
volumes:
  postgres_data:


