name: retrain fraud model job
on:
  schedule:
    - cron: "2 * * * *"
  workflow_dispatch:

env: 
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  retrain_model:
    runs-on: ubuntu-latest
    steps:
    # checkout code to the runner
      - name: checkout code
        uses: actions/checkout@v4.1.7

      - name: Login to Docker Hub             # usage and other container registries: https://github.com/marketplace/actions/docker-login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}      

      - name: setup docker  
        uses: docker/setup-buildx-action@v3
         
      - name: build and run containers
        run: | 
          docker compose up -d --build

      - name: check PostgreSQL tables
      run: |
        docker compose exec -e PGPASSWORD="password1" database psql -U postgres -d fraud_transactions -c '\dt'
    
      
      - name: commit and push to Dockerhub
        run: |
          docker commit app_contianer ${DOCKER_USERNAME}/model_production:latest
          docker push ${DOCKER_USERNAME}/model_production:latest

      - name: cleanup
        run: |
          docker compose down
          docker logout
        

