name: retrain model job
on:
  # schedule:
  #   - cron: "2 * * * *"
  workflow_dispatch:

env: 
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  # DOCKER_PROJECT_NAME: model_production
  # POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  # POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
jobs:
  retrain_model:
    runs-on: ubuntu-latest
    steps:
    # checkout code to the runner
      - name: checkout code
        uses: actions/checkout@v4.1.7
        with:
          lfs: true  

      # Install Git LFS
      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install
          git lfs pull
          ls

      # - name: confirm folder structure
      #   run: |
          
      - name: Login to Docker Hub             # usage and other container registries: https://github.com/marketplace/actions/docker-login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: setup docker  
        uses: docker/setup-buildx-action@v3

      - name: build and run containers
        run: | 
          docker compose up --build --abort-on-container-exit || true
          echo "Commiting and pushing to docker hub:"
          docker commit app_container ${DOCKER_USERNAME}/model_production:latest
          docker push ${DOCKER_USERNAME}/model_production:latest
          docker compose down
      # - name: Print database logs
      #   run: docker compose down
      # docker commit app_contianer ${DOCKER_USERNAME}/model_production:latest
      
      - name: commit and push to Dockerhub
        run: |
          docker push ${DOCKER_USERNAME}/model_production:latest
      - name: cleanup
        run: |
          docker compose down
          docker logout

