name: retrain fraud model job
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
env: 
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PROJECT_NAME: model_production
jobs:
  retrain_model:
    runs-on: ubuntu-latest
    steps:
    # checkout code to the runner
      - name: checkout code
        uses: actions/checkout@v4.1.7

      - name: Login to Docker Hub             # usage and other container registries: https://github.com/marketplace/actions/docker-login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: setup docker  
        uses: docker/setup-buildx-action@v3
         
      - name: build and run containers
        run: | 
          docker compose up -d database mlflow 
          
      
      - name: commit and push to Dockerhub
        run: |
          docker commit mlflow_container triggertiger/model_production:mlflow
          docker push myuser/myproject:mlflow


      # - name: commit and push changes to github
      #   env: 
      #     PUSH_ACCESS_TOKEN: ${{ secrets.PUSH_ACCESS_TOKEN }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git add mlruns/*
      #     git commit -m "new model version [skip ci]"   
      #     git remote set-url origin https://x-access-token:${PUSH_ACCESS_TOKEN}@github.com/${{ github.repository }}.git
      #     git push

      
      - name: cleanup
        run: |
          docker compose down
          docker logout
        

