name: retrain model job
on:
  schedule:
    - cron: "2 * * * *"
  workflow_dispatch:

env: 
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  # DOCKER_PROJECT_NAME: model_production
  # POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  # POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
jobs:
  retrain_model:
    runs-on: ubuntu-latest
    steps:
    # checkout code to the runner
      - name: checkout code
        uses: actions/checkout@v4.1.7

      - name: Login to Docker Hub             # usage and other container registries: https://github.com/marketplace/actions/docker-login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: setup docker  
        uses: docker/setup-buildx-action@v3

      - name: build and run containers
        run: | 
          docker compose up --build
          docker ps

      
      - name: Print database logs
        run: docker compose logs database
        
      # - name: check PostgreSQL tables
      #   run: |
      #     docker exec  database -e POSTGRES_PASSWORD=password1 psql -U postgres -d fraud_transactions -c '\dt'
          
      
      - name: commit and push to Dockerhub
        run: |
          docker commit app_contianer ${DOCKER_USERNAME}/model_production:latest
          docker push ${DOCKER_USERNAME}/model_production:latest
      - name: cleanup
        run: |
          docker compose down
          docker logout

